version: '3.3'
services:
  server:
    build: .
    #volumes:
    #  - ./:/usr/src/app
    command: node server.js
    ports:
      - "9233:9233"
  client:
    build: .
    #volumes:
    #  - ./:/usr/src/app
    environment:
      - SERVER=server
    command: node client.js
    depends_on:
      - server
